<a href="https://colab.research.google.com/github/goutham3010/Hospital-Readmission-Prediction-System/blob/main/2_Exploratory_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as ans
import matplotlib.pyplot as plt
import numpy as np
df=pd.read_csv("/content/hospital_readmission_dataset.csv")

In [ ]:
df.head()

,patient_id,admission_date,season,age,gender,region,primary_diagnosis,comorbidities_count,length_of_stay,treatment_type,medications_count,followup_visits_last_year,prev_readmissions,insurance_type,discharge_disposition,readmission_risk_score,label
0,P00001,2022-04-14,Spring,66,Male,South,Diabetes,5,6,Interventional,8,6,1,Medicare,Home Health,0.92,1
1,P00002,2021-09-19,Fall,55,Male,South,Diabetes,4,6,Interventional,6,4,3,Private,Home Health,0.88,1
2,P00003,2023-04-12,Spring,69,Female,West,Hypertension,6,8,Medical,9,6,2,Medicare,Skilled Nursing,0.97,1
3,P00004,2023-08-14,Summer,83,Male,South,Stroke,6,11,Medical,11,4,2,Medicare,Skilled Nursing,0.97,1
4,P00005,2021-11-05,Fall,54,Female,North,Stroke,4,10,Medical,6,2,1,Uninsured,Home Health,0.83,1

In [ ]:
df.describe()

,age,comorbidities_count,length_of_stay,medications_count,followup_visits_last_year,prev_readmissions,readmission_risk_score,label
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.00000,8000.000000,8000.000000
mean,57.411625,4.318500,7.789125,7.475750,3.638125,1.57250,0.776937,0.772875
std,16.724388,1.358046,1.930252,2.287917,1.630415,0.89196,0.219885,0.419000
min,18.000000,1.000000,3.000000,2.000000,0.000000,0.00000,0.070000,0.000000
25%,46.000000,3.000000,6.000000,6.000000,2.000000,1.00000,0.630000,1.000000
50%,57.000000,4.000000,8.000000,8.000000,4.000000,1.00000,0.860000,1.000000
75%,69.000000,5.000000,9.000000,9.000000,4.000000,2.00000,0.970000,1.000000
max,95.000000,10.000000,15.000000,18.000000,10.000000,5.00000,0.970000,1.000000

In [ ]:
num_rows=[
    "age",
    "comorbidities_count",
    "length_of_stay",
    "medications_count",
    "followup_visits_last_year",
    "prev_readmissions"
]
df[num_rows].describe()

,age,comorbidities_count,length_of_stay,medications_count,followup_visits_last_year,prev_readmissions
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.00000
mean,57.411625,4.318500,7.789125,7.475750,3.638125,1.57250
std,16.724388,1.358046,1.930252,2.287917,1.630415,0.89196
min,18.000000,1.000000,3.000000,2.000000,0.000000,0.00000
25%,46.000000,3.000000,6.000000,6.000000,2.000000,1.00000
50%,57.000000,4.000000,8.000000,8.000000,4.000000,1.00000
75%,69.000000,5.000000,9.000000,9.000000,4.000000,2.00000
max,95.000000,10.000000,15.000000,18.000000,10.000000,5.00000

In [ ]:
df.shape

(8000, 17)

In [19]:
df.duplicated().sum()

np.int64(0)